// frontend-vue/src/components/save/CategoryTabs.vue
<script setup lang="ts">
import GhibliIcon from "@/components/icons/GhibliIcon.vue";

defineProps({
  modelValue: {
    type: String,
    required: true,
  },
  categories: {
    type: Array,
    required: true,
  },
});

defineEmits(["update:modelValue"]);
</script>

<template>
  <div class="sub-tabs">
    <button
      v-for="x in categories"
      :key="x.id"
      class="sub-tab"
      :class="{ active: modelValue === x.id }"
      @click="$emit('update:modelValue', x.id)"
    >
      <span class="st-ico"><GhibliIcon :type="x.ico" size="16" /></span>
      {{ x.label }}
    </button>
  </div>
</template>

// frontend/src/components/save/CategoryTabs.tsx
import GhibliIcon from "@/components/icons/GhibliIcon";
import type { Category } from "@/types";

interface CategoryTabsProps {
  value: string;
  categories: Category[];
  onChange: (catId: string) => void;
}

export default function CategoryTabs({
  value,
  categories,
  onChange,
}: CategoryTabsProps) {
  return (
    <div className="sub-tabs">
      {categories.map((x) => (
        <button
          key={x.id}
          className={`sub-tab ${value === x.id ? "active" : ""}`}
          onClick={() => onChange(x.id)}
          type="button"
        >
          <span className="st-ico">
            <GhibliIcon type={x.ico} size={16} />
          </span>
          {x.label}
        </button>
      ))}
    </div>
  );
}
