// frontend-vue/src/components/save/SaveItemCard.vue
<script setup lang="ts">
import GhibliIcon from "@/components/icons/GhibliIcon.vue";

defineProps({
  item: {
    type: Object,
    required: true,
  },
  categoryIcon: {
    type: String,
    required: true,
  },
});

defineEmits(["edit", "delete"]);
</script>

<template>
  <div class="item-card">
    <img v-if="item.image" class="item-img" :src="item.image" :alt="item.title" />
    <div v-else class="no-img">
      <GhibliIcon :type="categoryIcon" size="50" />
    </div>
    <div class="item-body">
      <div class="item-title">{{ item.title }}</div>
      <div class="item-desc">{{ item.desc }}</div>
      <span v-if="item.tag" class="item-tag">{{ item.tag }}</span>
      <div class="item-actions">
        <button class="btn btn-secondary btn-small" @click="$emit('edit', item.id)">Sửa</button>
        <button class="btn btn-danger btn-small" @click="$emit('delete', item.id)">Xoá</button>
      </div>
    </div>
  </div>
</template>

// frontend/src/components/save/SaveItemCard.tsx
import GhibliIcon from "@/components/icons/GhibliIcon";
import type { SaveItem } from "@/types";

interface SaveItemCardProps {
  item: SaveItem;
  categoryIcon: string;
  onEdit: (id: string) => void;
  onDelete: (id: string) => void;
}

export default function SaveItemCard({
  item,
  categoryIcon,
  onEdit,
  onDelete,
}: SaveItemCardProps) {
  return (
    <div className="item-card">
      {item.image ? (
        <img className="item-img" src={item.image} alt={item.title} />
      ) : (
        <div className="no-img">
          <GhibliIcon type={categoryIcon} size={50} />
        </div>
      )}
      <div className="item-body">
        <div className="item-title">{item.title}</div>
        <div className="item-desc">{item.desc}</div>
        {item.tag && <span className="item-tag">{item.tag}</span>}
        <div className="item-actions">
          <button
            className="btn btn-secondary btn-small"
            onClick={() => onEdit(item.id)}
            type="button"
          >
            Sửa
          </button>
          <button
            className="btn btn-danger btn-small"
            onClick={() => onDelete(item.id)}
            type="button"
          >
            Xoá
          </button>
        </div>
      </div>
    </div>
  );
}
