// frontend/src/components/NavBar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { useRoute, useRouter } from "vue-router";
import GhibliIcon from "./icons/GhibliIcon.vue";
import { SAVE_CATEGORIES, GIFT_MODES } from "@/data/mock";

const route = useRoute();
const router = useRouter();

const openDD = ref(null);

const toggleDD = (name, event) => {
  if (event) event.stopPropagation();
  openDD.value = openDD.value === name ? null : name;
};

const closeDD = () => {
  openDD.value = null;
};

const go = (path) => {
  openDD.value = null;
  router.push(path);
};

const goSave = (catId) => {
  openDD.value = null;
  router.push({ path: "/save", query: { cat: catId } });
};

const goGift = (modeId) => {
  openDD.value = null;
  router.push({ path: "/gift", query: { mode: modeId } });
};

onMounted(() => {
  window.addEventListener("click", closeDD);
});

onUnmounted(() => {
  window.removeEventListener("click", closeDD);
});
</script>

<template>
  <nav class="nav-bar">
    <!-- Trang chủ -->
    <div class="nav-item">
      <button class="nav-btn" :class="{ active: route.path === '/' }" @click="go('/')">
        <GhibliIcon type="totoro" size="20" class="nav-ico" />
        <span>Trang chủ</span>
      </button>
    </div>

    <!-- Lưu mọi thứ (Dropdown) -->
    <div class="nav-item" :class="{ open: openDD === 'save' }" @click.stop>
      <button
        class="nav-btn"
        :class="{ active: route.path === '/save' }"
        @click="toggleDD('save', $event)"
      >
        <GhibliIcon type="soot" size="20" class="nav-ico" />
        <span>Lưu mọi thứ</span>
        <span class="arrow">▼</span>
      </button>
      <div class="nav-dropdown">
        <button
          v-for="c in SAVE_CATEGORIES"
          :key="c.id"
          class="dd-item"
          :class="{ active: route.path === '/save' && route.query.cat === c.id }"
          @click="goSave(c.id)"
        >
          <GhibliIcon :type="c.ico" size="18" class="dd-ico" />
          <span>{{ c.label }}</span>
        </button>
      </div>
    </div>

    <!-- Ngày bên nhau -->
    <div class="nav-item">
      <button
        class="nav-btn"
        :class="{ active: route.path === '/calendar' }"
        @click="go('/calendar')"
      >
        <GhibliIcon type="heart" size="20" class="nav-ico" />
        <span>Ngày bên nhau</span>
      </button>
    </div>

    <!-- Gợi ý quà (Dropdown) -->
    <div class="nav-item" :class="{ open: openDD === 'gift' }" @click.stop>
      <button
        class="nav-btn"
        :class="{ active: route.path === '/gift' }"
        @click="toggleDD('gift', $event)"
      >
        <GhibliIcon type="calcifer" size="20" class="nav-ico" />
        <span>Gợi ý quà</span>
        <span class="arrow">▼</span>
      </button>
      <div class="nav-dropdown">
        <button
          v-for="m in GIFT_MODES"
          :key="m.id"
          class="dd-item"
          :class="{ active: route.path === '/gift' && route.query.mode === m.id }"
          @click="goGift(m.id)"
        >
          <span>{{ m.label }}</span>
        </button>
      </div>
    </div>

    <!-- Gợi ý hẹn hò -->
    <div class="nav-item">
      <button class="nav-btn" :class="{ active: route.path === '/date' }" @click="go('/date')">
        <GhibliIcon type="soot" size="20" class="nav-ico" />
        <span>Gợi ý hẹn hò</span>
      </button>
    </div>
  </nav>
</template>

// frontend/src/components/NavBar.tsx
"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type React from "react";
import { Suspense, useCallback, useEffect, useState } from "react";
import { GIFT_MODES, SAVE_CATEGORIES } from "@/data/mock";
import GhibliIcon from "./icons/GhibliIcon";

function NavBarContent() {
  const pathname = usePathname();
  const router = useRouter();
  const searchParams = useSearchParams();

  const [openDD, setOpenDD] = useState<string | null>(null);

  const currentCat = searchParams ? searchParams.get("cat") : null;
  const currentMode = searchParams ? searchParams.get("mode") : null;

  const toggleDD = (name: string, event: React.MouseEvent) => {
    event.stopPropagation();
    setOpenDD((prev) => (prev === name ? null : name));
  };

  const closeDD = useCallback(() => {
    setOpenDD(null);
  }, []);

  useEffect(() => {
    window.addEventListener("click", closeDD);
    return () => {
      window.removeEventListener("click", closeDD);
    };
  }, [closeDD]);

  const goSave = (catId: string) => {
    setOpenDD(null);
    router.push(`/save?cat=${catId}`);
  };

  const goGift = (modeId: string) => {
    setOpenDD(null);
    router.push(`/gift?mode=${modeId}`);
  };

  return (
    <nav className="nav-bar">
      {/* Trang chủ */}
      <div className="nav-item">
        <Link
          href="/"
          className={`nav-btn ${pathname === "/" ? "active" : ""}`}
        >
          <GhibliIcon type="totoro" size={20} className="nav-ico" />
          <span>Trang chủ</span>
        </Link>
      </div>

      {/* Lưu mọi thứ (Dropdown) */}
      <div
        className={`nav-item ${openDD === "save" ? "open" : ""}`}
        onClick={(e) => e.stopPropagation()}
      >
        <button
          className={`nav-btn ${pathname === "/save" ? "active" : ""}`}
          onClick={(e) => toggleDD("save", e)}
          type="button"
        >
          <GhibliIcon type="soot" size={20} className="nav-ico" />
          <span>Lưu mọi thứ</span>
          <span className="arrow">▼</span>
        </button>
        <div className="nav-dropdown">
          {SAVE_CATEGORIES.map((c) => (
            <button
              key={c.id}
              className={`dd-item ${
                pathname === "/save" && currentCat === c.id ? "active" : ""
              }`}
              onClick={() => goSave(c.id)}
              type="button"
            >
              <GhibliIcon type={c.ico} size={18} className="dd-ico" />
              <span>{c.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Ngày bên nhau */}
      <div className="nav-item">
        <Link
          href="/calendar"
          className={`nav-btn ${pathname === "/calendar" ? "active" : ""}`}
        >
          <GhibliIcon type="heart" size={20} className="nav-ico" />
          <span>Ngày bên nhau</span>
        </Link>
      </div>

      {/* Gợi ý quà (Dropdown) */}
      <div
        className={`nav-item ${openDD === "gift" ? "open" : ""}`}
        onClick={(e) => e.stopPropagation()}
      >
        <button
          className={`nav-btn ${pathname === "/gift" ? "active" : ""}`}
          onClick={(e) => toggleDD("gift", e)}
          type="button"
        >
          <GhibliIcon type="calcifer" size={20} className="nav-ico" />
          <span>Gợi ý quà</span>
          <span className="arrow">▼</span>
        </button>
        <div className="nav-dropdown">
          {GIFT_MODES.map((m) => (
            <button
              key={m.id}
              className={`dd-item ${
                pathname === "/gift" && currentMode === m.id ? "active" : ""
              }`}
              onClick={() => goGift(m.id)}
              type="button"
            >
              <span>{m.label}</span>
            </button>
          ))}
        </div>
      </div>

      {/* Gợi ý hẹn hò */}
      <div className="nav-item">
        <Link
          href="/date"
          className={`nav-btn ${pathname === "/date" ? "active" : ""}`}
        >
          <GhibliIcon type="soot" size={20} className="nav-ico" />
          <span>Gợi ý hẹn hò</span>
        </Link>
      </div>
    </nav>
  );
}

export default function NavBar() {
  return (
    <Suspense fallback={<div className="nav-bar-loading">Loading...</div>}>
      <NavBarContent />
    </Suspense>
  );
}
